name: Test
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Test Suite
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: crate-py/rpds
          ref: main
          path: maturin
      - uses: actions/setup-python@v5
        with:
          python-version: pypy3.9
      - name: maturin build windows pypy
        uses: ./
        with:
          args: -o dist --interpreter pypy3.9
          working-directory: maturin
